### ISSUE TITLE
Unable to run scripts and executables

### ISSUE THREAD

**Issue by EnforcerE** [openzfsonwindows/openzfs#472]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Windows 10
Distribution Version	|10.0.19045.5796
Kernel Version	|10.0.19041.5794
Architecture	|x86_64
OpenZFS Version	|2.3.1rc4usb2

### Describe the problem you're observing
Windows doesn't run batch scripts and certain executables. As is seen in the screenshot when trying to run the scripts as admin, it complains of a network error. There are no spaces in the filename. This regression came somewhere between 2.3.0rc6 and 2.3.1rc4usb2 as that is the previous version that I had. I am unable to downgrade.

### Describe how to reproduce the problem
Import a pool and try to run a batch script.

### Include any warning/errors/backtraces from the system logs
None are available

![Image](https://github.com/user-attachments/assets/30a5bffc-7806-4818-9a5a-9584c025d78f)

**Comment by andrebraga** [comment]
This one is very likely a duplicate of #442.

Try this as a workaround:
https://github.com/openzfsonwindows/openzfs/issues/446#issuecomment-2658694691

**Comment by EnforcerE** [comment]
Ok this has worked for executing things, but permissions are now messed up. And changing the owner (and owner permissions to full control) for everything to my account doesn't work. Steam and battle.net are unable  to write to their respective folders. Steam says "Missing file privileges" and Battle.net says BLZBNTAGT00001398 (a very generic error code as far as I can say). Should this be a separate issue?

**Comment by andrebraga** [comment]
No, this would probably be a manifestation of another issue: #469

**Comment by andrebraga** [comment]
@lundman 👆

**Comment by EnforcerE** [comment]
Steam isn't being run from ZFS and as far as I understand #469 it affects executables run from ZFS. Steam is trying to write into ZFS. Same with battle.net. In fact executables are running perfectly well from ZFS.

**Comment by andrebraga** [comment]
#469 is about permissions. Executables run, but if they try to modify files in a given way they will likely fail.

**Comment by EnforcerE** [comment]
Solved in 2.3.1rc5

**Comment by guenther-alka** [comment]
still a problem my case
https://github.com/openzfsonwindows/openzfs/discussions/461#discussioncomment-13024216
